server:
  port: 8096


#spring.application.name
#spring.sleuth.sampler.percentage
#spring.zipkin.base-url
spring:
  application:
    name: microservice-userinfo
  sleuth:
    sampler:
      #采样率
      percentage: 1.0
  zipkin:
    #zipkin服务的地址
    base-url: http://localhost:9411

#配制debug打开
logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: debug

debug: true

