spring:
  application:
    name: data-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver2:8874/eureka,http://eurekaserver1:9992/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}


---
spring:
  profiles: client1
server:
  port: 6651

---
spring:
  profile: client2
server:
  port: 6652


---
spring:
  profile: client3
server:
  port: 6655
