spring:
  application:
    name: data-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver1:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}


---
spring:
  profiles: client1
server:
  port: 6661

---
spring:
  profile: client2
server:
  port: 6662
