spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  server:
    #eureka进行同步延迟的时间
    wait-time-in-ms-when-sync-empty: 0
    #eureka是否启用自保护模式
    enable-self-preservation: false



---
spring:
  profiles: eureka-server1
server:
  port: 8874
eureka:
  instance:
    hostname: eurekaserver1
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eurekaserver2:9992/eureka


---
spring:
  profiles: eureka-server2
server:
  port: 9992
eureka:
  instance:
    hostname: eurekaserver2
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eurekaserver1:8874/eureka

